# Generated by Django 3.0.6 on 2020-05-10 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20200510_1203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='status',
            field=models.IntegerField(choices=[('True', 'True'), ('False', 'False')]),
        ),
    ]
