# Generated by Django 3.0.6 on 2020-05-15 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0015_auto_20200513_0356'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='discount_home',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='product',
            name='men_home',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='product',
            name='new_arrival',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='product',
            name='women_home',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
