# Generated by Django 3.0.6 on 2020-05-16 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0019_product_short_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.TextField(choices=[('True', 'True'), ('False', 'False')], max_length=10),
        ),
    ]
