# Generated by Django 3.0.6 on 2020-05-16 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0021_auto_20200516_1120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='short_description',
            field=models.TextField(default=True, max_length=100),
        ),
    ]
