# Generated by Django 3.0.6 on 2020-05-12 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_contactmessages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactmessages',
            name='status',
            field=models.CharField(choices=[('New', 'New'), ('New', 'Read')], default='New', max_length=3),
        ),
        migrations.AlterField(
            model_name='contactmessages',
            name='telephone',
            field=models.CharField(max_length=14),
        ),
    ]
