# Generated by Django 3.0.6 on 2020-05-13 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20200512_1338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactmessages',
            name='status',
            field=models.CharField(choices=[('New', 'New'), ('Read', 'Read')], default='New', max_length=4),
        ),
    ]
