# Generated by Django 3.0.6 on 2020-05-13 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20200513_0317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactmessages',
            name='status',
            field=models.CharField(choices=[('New', 'New'), ('Read', 'Read'), ('Closed', 'Closed')], default='New', max_length=6),
        ),
    ]
